### ISSUE TITLE
关于合成结果耐久附魔的BUG反馈

### ISSUE THREAD

**Issue by Conquerski** [ChiyodaXiaoYi/OasisRecipe#1]
在results里面通过import导入添加的物品，含有耐久3的附魔
  enchants:
  - DURABILITY 3
 
执行插件reload的时候，控制台报错
[OasisRecipe] INFO | durability is not a valid enchant type

将DURABILITY 3 更换为 MENDING 1后，插件正常reload。

目前没有测试是否有其他附魔存在同样问题。

**Comment by ChiyodaXiaoYi** [comment]
已修复，请使用0.1.2版本
